### ISSUE TITLE
Links in the Other section 404

### ISSUE THREAD

**Issue by jschoolcraft** [bkuhlmann/pennyworth#1]
## Overview
Links in the [Other section](https://github.com/bkuhlmann/pennyworth#other) 404

## Screenshots/Screencasts

![image](https://user-images.githubusercontent.com/18264/120823103-12837900-c525-11eb-9e8f-4dfdd348f74b.png)

## Steps to Recreate

Click on one of the links

## Desired Behavior

To see the linked resource.

## Environment

MacOS, I'm using Brave.

**Comment by bkuhlmann** [comment]
:bow: **Jeff**. What happens when you right click and "save as" does that work as per the documentation suggested in the README?

**Comment by bkuhlmann** [comment]
:information_source: This is fixed now. If you refresh the page, you'll find all workflows will download properly now without the need to right click. The problem was two-fold:

- Link typo.
- Wrong content disposition set on AWS S3.
